### ISSUE TITLE
Animation trigger area

### ISSUE THREAD

**Issue by SelfRef** [icedman/dash-animator#1]
Trigger area that makes animation active is only on icon itself. That causes animation not being active when cursor is on icon outer rectangle as well as outside icon rectangle (dock background). In effect the animation is jiggering when moving cursor too low or too high and doesn't work at all when cursor is at the bottom edge of screen (icon still can be clicked).

![Screenshot from 2022-07-26 11-33-42](https://user-images.githubusercontent.com/69125050/180981554-3ee2c30e-2b13-4e93-ba83-3343d58b1fad.png)

My suggestion is to use entire dock as activator for animation then enlarge icons in proportion to the distance from the cursor. macOS dock animation could be the best example.

BTW, very cool extension, I was looking for something like this.

**Comment by icedman** [comment]
This has been addressed. Smoother animation and larger hit area will be included in the next update. Ty!
