### ISSUE TITLE
dash to dock is not available for gnome 42

### ISSUE THREAD

**Issue by AbhishekZambaremPHATEK** [icedman/dash-animator#4]
please make compatible to "dash-to-dock-for-cosmic" which is same bcz dash to dock is not available for gnome 42

**Comment by icedman** [comment]
I pushed the latest changes to the main branch. And tested OK with dash-to-dock-cosmic-halfmexican with the setup:
OS: Arch Linux x86_64 
Host: XPS 13 9350 
Kernel: 5.15.55-1-lts 
Uptime: 2 days, 14 hours, 34 mins 
Packages: 1158 (pacman) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: GNOME 42.3.1 
WM: Mutter 
WM Theme: Adwaita
