### ISSUE TITLE
Not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by slick92** [icedman/dash-animator#6]
The extension doesn't seem to be working on Ubuntu 22.04. Tried using the extensions manager app as well directly cloning the github repo. Tried with both the Ubuntu Dock as well as Dash to Dock. Disabled all other extensions that alter the dock (e.g. Blur My Shell)

```
S ERROR: TypeError: bin is null
_findIcons/<@/home/slick/.local/share/gnome-shell/extensions/dash-animator@icedman.github.com/extension.js:219:18
_findIcons@/home/slick//.local/share/gnome-shell/extensions/dash-animator@icedman.github.com/extension.js:209:14
_updateIcons@/home/slick//.local/share/gnome-shell/extensions/dash-animator@icedman.github.com/extension.js:287:22
_animate@/home/slick//.local/share/gnome-shell/extensions/dash-animator@icedman.github.com/extension.js:200:10
wrappedFunc@/home/slick//.local/share/gnome-shell/extensions/dash-animator@icedman.github.com/utils.js:12:17

Source ID 67934 was not found when attempting to remove it
```

**Comment by icedman** [comment]
I pushed a possible fix.  Could you upload a screenshot of your dock without the animator? I suspect you have other icons on the dock such as Trash bin or may network mounts.

You could also try https://github.com/icedman/dash2dock-lite 
It is an animated dock - no need for dash to dock extension. Supports only bottom layout though

**Comment by slick92** [comment]
I removed all the trash bin and network mounts from the dock and tried again; disabled dash-to-dock and used the default ubuntu dock; tried in X11 and Wayland. Unfortunately I couldn't get it to work.

The dash2dock-lite did work though. I am not familiar with how extensions work, but would comparing the configs of dash2dock-lite and dash-to-dock from dconf yield anything of interest ?

I will test out the extension on a fresh VM and post the results.

**Comment by slick92** [comment]
Tested on a fresh VM with only dash-to-dock and dash-animator, it is working. This issue can be closed since it seems to be environment specific.
