### ISSUE TITLE
Last version adss a stange icon in panel bar on the left

### ISSUE THREAD

**Issue by Neo-29** [icedman/dash-animator#9]
Bug here....
![image](https://user-images.githubusercontent.com/90937180/194751154-b4788700-770e-4b62-8bf2-a157a56746c3.png)

Don't know whatś that icon on the left...but ugly and useless

**Comment by icedman** [comment]
That's the app icon. What Dock are you using? Do you hide the app icon with JustPerfection?

Possible temporary fix - just show the apps icons (maybe from JustPerfection). Few months ago, I hid that app icon. People requested to have it shown and animated.

**Comment by Neo-29** [comment]
I'm using dash to dock ( what else because this extension is made for it
Show app doesn't fix the issue. 
It's ugly and the icon not responding to anything. 
Last version brings a new issue too.

**Comment by icedman** [comment]
There is Cosmic & Ubuntu.

**Comment by Neo-29** [comment]
> There is Cosmic & Ubuntu.

It's still dash to dock

Nevermind.
Your extension is way to buggy.
I'll come back to it when correctly working and tested.
Thanks for your time anyway.
